### ISSUE TITLE
Application error is overridden with MQTT::NotConnectedException

### ISSUE THREAD

**Issue by yhara** [njh/ruby-em-mqtt#13]
When some error (eg. `JSON::ParserError`) is raised in an application, Ruby reports `MQTT::NotConnectedException` instead of the actual cause.

## Example

```rb
require 'em/mqtt'
require 'json'

EventMachine.run do
  c = ClientConnection.connect('test.mosquitto.org')
  JSON.parse("!$%&")  # raises json parse error
end
```

## Expected Result

`JSON::ParserError` is shown

## Actual Result

```
/Users/yhara/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/em-mqtt-0.0.4/lib/em/mqtt/client_connection.rb:109:in `unbind': Connection to server lost (MQTT::NotConnectedException)
        from /Users/yhara/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1465:in `event_callback'
        from /Users/yhara/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:202:in `release_machine'
        from /Users/yhara/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:202:in `ensure in run'
        from /Users/yhara/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:226:in `run'
        from c.rb:16:in `<main>'
```

## Possible fix

You can check `$!` to know why `#unbind` is called. (`$!` holds the last exception raised and not yet handled by `rescue`)

```diff
 # class EventMachine::MQTT::ClientConnection
   def unbind
     timer.cancel if timer
     unless state == :disconnecting
-      raise MQTT::NotConnectedException.new("Connection to server lost")
+      if $!
+        # Connection is lost because of an application error
+      else
+        raise MQTT::NotConnectedException.new("Connection to server lost")
+      end
     end
     @state = :disconnected
   end
```

**Comment by njh** [comment]
I have struggled with this problem a lot - it is one of the reasons why I haven't done much more development on it.

I thought that the problem was a mixture of exceptions and Deferrables. 

Looking at your code - I think the exception should be caught before unbind - rather than just giving a better error message when the connection is dropped?
